spring:
  datasource:
#    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#    username: ${PGUSER}
#    password: ${PGPASSWORD}
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:16546/railway
    username: postgres
    password: CArBbfxiDbtRNuZVSCeMVQMEJZeMeCDk
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
